schema_version: 1

context:
  version: '1.19'

package:
  name: popt
  version: ${{ version }}

source:
  url: https://github.com/rpm-software-management/popt/archive/refs/tags/popt-${{ version }}-release.tar.gz
  sha256: 6eb40d650526cb9fe63eb4415bcecdf9cf306f7556e77eff689abc5a44670060
  patches:
    - popt-windows-support.patch

build:
  number: 2

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - libiconv
    - if: unix
      then:
        - autoconf
        - automake
        - libtool
        - gettext-tools
        - gnuconfig
        - make
    - if: win
      then:
        - autotools_clang_conda
        - m2-gettext
        
  host:
    - libiconv
  run_exports:
    - ${{ pin_subpackage('popt', upper_bound='x') }}

tests:
  - package_contents:
      include:
        - popt.h
      lib:
        - popt
  - script:
      - if: win
        then: |
          @echo on
          @REM See https://github.com/prefix-dev/rattler-build/issues/2657
          cl /nologo /W4 /I"%LIBRARY_INC%" test_popt.c /link /LIBPATH:"%LIBRARY_LIB%" popt.lib /OUT:test_popt.exe
          test_popt.exe
          tasklist | findstr /I vctip || ver
          taskkill /F /IM vctip.exe >NUL 2>&1 || ver
    requirements:
      run:
        - if: win
          then:
            - ${{ compiler('c') }}
    files:
      recipe:
        - test_popt.c
    
about:
  homepage: http://ftp.rpm.org/popt
  repository: https://github.com/rpm-software-management/popt
  documentation: https://github.com/rpm-software-management/popt/blob/popt-${{ version }}-release/popt.pdf
  license: MIT
  license_file: COPYING
  summary: 'C library for parsing command line parameters'

extra:
  recipe-maintainers:
    - eunos-1128
    - notestaff
    - sodre
